services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.9.2
    environment:
      BASE_URL: ${DOMAIN}
      ALLOW_SIGNUP: "true"
      DB_ENGINE: sqlite
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - /mnt/applications/mealie:/app/data/
    networks:
      - traefik_default
    labels:
      traefik.enable: true
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.routers.mealie.rule: Host(`${DOMAIN}`)
    restart: unless-stopped

networks:
  traefik_default:
    external: true
