services:
  web:
    image: ghcr.io/jofoerster/habitsync:0.18.0
    user: "6842:6842"
    environment:
      - BASE_URL=https://${DOMAIN}/
      - APP_SECURITY_ISSUERS_POCKETID_URL=${POCKETID_URL}
      - APP_SECURITY_ISSUERS_POCKETID_CLIENT-ID=${POCKETID_CLIENT_ID}
      - APP_SECURITY_ISSUERS_POCKETID_NEEDS-CONFIRMATION=false
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_MAIL_ENABLED=false
    volumes:
      - /mnt/applications/habitsync:/data
    networks:
      - newt_default
    healthcheck:
      disable: true
    labels:
      - pangolin.proxy-resources.habitsync.name=HabitSync
      - pangolin.proxy-resources.habitsync.full-domain=${DOMAIN}
      - pangolin.proxy-resources.habitsync.protocol=http
      - pangolin.proxy-resources.habitsync.auth.sso-enabled=false
      - pangolin.proxy-resources.habitsync.targets[0].method=http
      - pangolin.proxy-resources.habitsync.targets[0].port=6842
    restart: unless-stopped

networks:
  newt_default:
    external: true
